steps:
- name: apply-template
  image: lachlanevenson/k8s-kubectl
  args:
  - apply
  - -f
  - knative-build-template.yaml
- name: apply-function
  image: lachlanevenson/k8s-kubectl
  args:
  - apply
  - -f
  - function.yaml
