steps:
- name: kubectl
  image: lachlanevenson/k8s-kubectl
  args:
  - apply
  - -f
  - knative-build-template.yaml
- name: kubectl
  image: lachlanevenson/k8s-kubectl
  args:
  - apply
  - -f
  - function.yaml
