source:
  git:
    url: https://github.com/sebgoa/azure-queue-func.git
    revision: master
steps:
- name: kubectl
  image: lachlanevenson/k8s-kubectl
  args:
  - kubectl
  - apply
  - -f
  - knative-build-template.yaml
- name: kubectl
  image: lachlanevenson/k8s-kubectl
  args:
  - kubectl
  - apply
  - -f
  - function.yaml
